#############################################################################
# Makefile for building: DBOX-MTCT
# Generated by qmake (3.1) (Qt 5.11.2)
# Project:  DBOX-MTCT.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile DBOX-MTCT.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_QML_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/opt/cuda/include -isystem /usr/local/include/suprema -I../../Git/fingerprint-extraction-lib -I../../Git/fingerprint-matching-lib -I../../Git/fingerprint-preprocessing-lib -isystem /usr/include/qt -isystem /usr/include/qt/QtPrintSupport -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib/qt/mkspecs/linux-g++
QMAKE         = /usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = DBOX-MTCT1.0.0
DISTDIR = /home/peterhutas/QtProjects/DBOX-MTCT/.tmp/DBOX-MTCT1.0.0
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS) -L/opt/cuda/lib64/ -lcudart -L/usr/local/lib/ -lUFMatcher -L/usr/lib/ -lopencv_core -lopencv_imgcodecs -lopencv_imgproc -lafcuda -lcaffe -lboost_system -lglog -lprotobuf -L/home/peterhutas/QtProjects/DBOX-MTCT/../../Git/fingerprint-extraction-lib/ -lExtraction -L/home/peterhutas/QtProjects/DBOX-MTCT/../../Git/fingerprint-matching-lib/ -lMatcher -L/home/peterhutas/QtProjects/DBOX-MTCT/../../Git/fingerprint-preprocessing-lib/ -lPreprocessing -lQt5PrintSupport -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		graphics_view_zoom.cpp \
		MinutiaeMarker/minutiaemarker.cpp \
		mousefingerprintscene.cpp \
		networktrainer.cpp \
		minutiaechecker.cpp \
		caffenetwork.cpp \
		databasetester.cpp \
		isoconverter.cpp \
		QCustomPlot/qcustomplot.cpp \
		extractiontester.cpp \
		Config/dbox_mtct_config.cpp \
		Config/minutia_config.cpp \
		MinutiaeMarker/minutia.cpp \
		MinutiaeMarker/Config/minutiaemarker_config.cpp \
		MinutiaeMarker/minutiaemarker_settings.cpp \
		MinutiaeMarker/Utils/minutiaemarker_dataaugmentationutils.cpp \
		image.cpp moc_mainwindow.cpp \
		moc_graphics_view_zoom.cpp \
		moc_minutiaemarker.cpp \
		moc_mousefingerprintscene.cpp \
		moc_networktrainer.cpp \
		moc_minutiaechecker.cpp \
		moc_caffenetwork.cpp \
		moc_databasetester.cpp \
		moc_isoconverter.cpp \
		moc_qcustomplot.cpp \
		moc_extractiontester.cpp
OBJECTS       = main.o \
		mainwindow.o \
		graphics_view_zoom.o \
		minutiaemarker.o \
		mousefingerprintscene.o \
		networktrainer.o \
		minutiaechecker.o \
		caffenetwork.o \
		databasetester.o \
		isoconverter.o \
		qcustomplot.o \
		extractiontester.o \
		dbox_mtct_config.o \
		minutia_config.o \
		minutia.o \
		minutiaemarker_config.o \
		minutiaemarker_settings.o \
		minutiaemarker_dataaugmentationutils.o \
		image.o \
		moc_mainwindow.o \
		moc_graphics_view_zoom.o \
		moc_minutiaemarker.o \
		moc_mousefingerprintscene.o \
		moc_networktrainer.o \
		moc_minutiaechecker.o \
		moc_caffenetwork.o \
		moc_databasetester.o \
		moc_isoconverter.o \
		moc_qcustomplot.o \
		moc_extractiontester.o
DIST          = Resources/MinutiaeIcons/BIFURCATION.png \
		Resources/MinutiaeIcons/BREAK.png \
		Resources/MinutiaeIcons/BRIDGE.png \
		Resources/MinutiaeIcons/CROSSBAR.png \
		Resources/MinutiaeIcons/DOCK.png \
		Resources/MinutiaeIcons/DOT.png \
		Resources/MinutiaeIcons/ENCLOSURE.png \
		Resources/MinutiaeIcons/OPPOSITE_BIFURCATIONS.png \
		Resources/MinutiaeIcons/OVERLAP.png \
		Resources/MinutiaeIcons/RETURN.png \
		Resources/MinutiaeIcons/SHORT_RIDGE.png \
		Resources/MinutiaeIcons/SPIKE.png \
		Resources/MinutiaeIcons/TERMINATION.png \
		Resources/MinutiaeIcons/TRIFURCATION.png \
		/usr/lib/qt/mkspecs/features/spec_pre.prf \
		/usr/lib/qt/mkspecs/common/unix.conf \
		/usr/lib/qt/mkspecs/common/linux.conf \
		/usr/lib/qt/mkspecs/common/sanitize.conf \
		/usr/lib/qt/mkspecs/common/gcc-base.conf \
		/usr/lib/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt/mkspecs/common/g++-base.conf \
		/usr/lib/qt/mkspecs/common/g++-unix.conf \
		/usr/lib/qt/mkspecs/qconfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_Attica.pri \
		/usr/lib/qt/mkspecs/modules/qt_Baloo.pri \
		/usr/lib/qt/mkspecs/modules/qt_BluezQt.pri \
		/usr/lib/qt/mkspecs/modules/qt_KActivities.pri \
		/usr/lib/qt/mkspecs/modules/qt_KActivitiesStats.pri \
		/usr/lib/qt/mkspecs/modules/qt_KArchive.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAuth.pri \
		/usr/lib/qt/mkspecs/modules/qt_KBookmarks.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCMUtils.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCodecs.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCompletion.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCrash.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDBusAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDeclarative.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDESu.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDNSSD.pri \
		/usr/lib/qt/mkspecs/modules/qt_KEmoticons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KFileMetaData.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGlobalAccel.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGuiAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KHolidays.pri \
		/usr/lib/qt/mkspecs/modules/qt_KHtml.pri \
		/usr/lib/qt/mkspecs/modules/qt_KI18n.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIconThemes.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIdleTime.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOFileWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_Kirigami2.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemModels.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemViews.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJobWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJS.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJSApi.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJsEmbed.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNewStuff.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNewStuffCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNotifications.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNotifyConfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNTLM.pri \
		/usr/lib/qt/mkspecs/modules/qt_KParts.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPeople.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPeopleWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPty.pri \
		/usr/lib/qt/mkspecs/modules/qt_KRunner.pri \
		/usr/lib/qt/mkspecs/modules/qt_KScreen.pri \
		/usr/lib/qt/mkspecs/modules/qt_KService.pri \
		/usr/lib/qt/mkspecs/modules/qt_KSyntaxHighlighting.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTextEditor.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTextWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KUnitConversion.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWallet.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWaylandClient.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWaylandServer.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWidgetsAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWindowSystem.pri \
		/usr/lib/qt/mkspecs/modules/qt_KXmlGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dtkcore.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dtkwidget.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dtkwm.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_ModemManagerQt.pri \
		/usr/lib/qt/mkspecs/modules/qt_NetworkManagerQt.pri \
		/usr/lib/qt/mkspecs/modules/qt_phonon4qt5.pri \
		/usr/lib/qt/mkspecs/modules/qt_Prison.pri \
		/usr/lib/qt/mkspecs/modules/qt_QuickAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_Solid.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetUi.pri \
		/usr/lib/qt/mkspecs/modules/qt_ThreadWeaver.pri \
		/usr/lib/qt/mkspecs/features/qt_functions.prf \
		/usr/lib/qt/mkspecs/features/qt_config.prf \
		/usr/lib/qt/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt/mkspecs/features/toolchain.prf \
		/usr/lib/qt/mkspecs/features/default_pre.prf \
		/usr/lib/qt/mkspecs/features/resolve_config.prf \
		/usr/lib/qt/mkspecs/features/default_post.prf \
		/usr/lib/qt/mkspecs/features/qml_debug.prf \
		/usr/lib/qt/mkspecs/features/warn_on.prf \
		/usr/lib/qt/mkspecs/features/qt.prf \
		/usr/lib/qt/mkspecs/features/resources.prf \
		/usr/lib/qt/mkspecs/features/moc.prf \
		/usr/lib/qt/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt/mkspecs/features/uic.prf \
		/usr/lib/qt/mkspecs/features/unix/thread.prf \
		/usr/lib/qt/mkspecs/features/qmake_use.prf \
		/usr/lib/qt/mkspecs/features/file_copies.prf \
		/usr/lib/qt/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt/mkspecs/features/exceptions.prf \
		/usr/lib/qt/mkspecs/features/yacc.prf \
		/usr/lib/qt/mkspecs/features/lex.prf \
		DBOX-MTCT.pro mainwindow.h \
		graphics_view_zoom.h \
		MinutiaeMarker/minutiaemarker.h \
		mousefingerprintscene.h \
		networktrainer.h \
		minutiaechecker.h \
		caffenetwork.h \
		databasetester.h \
		isoconverter.h \
		qmatconverter.h \
		QCustomPlot/qcustomplot.h \
		extractiontester.h \
		helper.h \
		MinutiaeMarker/minutia.h \
		ui_mainwindow.h \
		Config/dbox_mtct_config.h \
		Config/minutia_config.h \
		MinutiaeMarker/minutiaemarker_settings.h \
		MinutiaeMarker/Utils/minutiaemarker_dataaugmentationutils.h \
		MinutiaeMarker/Config/minutiamarker_config.h \
		image.h main.cpp \
		mainwindow.cpp \
		graphics_view_zoom.cpp \
		MinutiaeMarker/minutiaemarker.cpp \
		mousefingerprintscene.cpp \
		networktrainer.cpp \
		minutiaechecker.cpp \
		caffenetwork.cpp \
		databasetester.cpp \
		isoconverter.cpp \
		QCustomPlot/qcustomplot.cpp \
		extractiontester.cpp \
		Config/dbox_mtct_config.cpp \
		Config/minutia_config.cpp \
		MinutiaeMarker/minutia.cpp \
		MinutiaeMarker/Config/minutiaemarker_config.cpp \
		MinutiaeMarker/minutiaemarker_settings.cpp \
		MinutiaeMarker/Utils/minutiaemarker_dataaugmentationutils.cpp \
		image.cpp
QMAKE_TARGET  = DBOX-MTCT
DESTDIR       = 
TARGET        = DBOX-MTCT


first: all
####### Build rules

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: DBOX-MTCT.pro /usr/lib/qt/mkspecs/linux-g++/qmake.conf /usr/lib/qt/mkspecs/features/spec_pre.prf \
		/usr/lib/qt/mkspecs/common/unix.conf \
		/usr/lib/qt/mkspecs/common/linux.conf \
		/usr/lib/qt/mkspecs/common/sanitize.conf \
		/usr/lib/qt/mkspecs/common/gcc-base.conf \
		/usr/lib/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt/mkspecs/common/g++-base.conf \
		/usr/lib/qt/mkspecs/common/g++-unix.conf \
		/usr/lib/qt/mkspecs/qconfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_Attica.pri \
		/usr/lib/qt/mkspecs/modules/qt_Baloo.pri \
		/usr/lib/qt/mkspecs/modules/qt_BluezQt.pri \
		/usr/lib/qt/mkspecs/modules/qt_KActivities.pri \
		/usr/lib/qt/mkspecs/modules/qt_KActivitiesStats.pri \
		/usr/lib/qt/mkspecs/modules/qt_KArchive.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAuth.pri \
		/usr/lib/qt/mkspecs/modules/qt_KBookmarks.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCMUtils.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCodecs.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCompletion.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCrash.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDBusAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDeclarative.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDESu.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDNSSD.pri \
		/usr/lib/qt/mkspecs/modules/qt_KEmoticons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KFileMetaData.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGlobalAccel.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGuiAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KHolidays.pri \
		/usr/lib/qt/mkspecs/modules/qt_KHtml.pri \
		/usr/lib/qt/mkspecs/modules/qt_KI18n.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIconThemes.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIdleTime.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOFileWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_Kirigami2.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemModels.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemViews.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJobWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJS.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJSApi.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJsEmbed.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNewStuff.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNewStuffCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNotifications.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNotifyConfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNTLM.pri \
		/usr/lib/qt/mkspecs/modules/qt_KParts.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPeople.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPeopleWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPty.pri \
		/usr/lib/qt/mkspecs/modules/qt_KRunner.pri \
		/usr/lib/qt/mkspecs/modules/qt_KScreen.pri \
		/usr/lib/qt/mkspecs/modules/qt_KService.pri \
		/usr/lib/qt/mkspecs/modules/qt_KSyntaxHighlighting.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTextEditor.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTextWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KUnitConversion.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWallet.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWaylandClient.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWaylandServer.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWidgetsAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWindowSystem.pri \
		/usr/lib/qt/mkspecs/modules/qt_KXmlGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dtkcore.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dtkwidget.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dtkwm.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_ModemManagerQt.pri \
		/usr/lib/qt/mkspecs/modules/qt_NetworkManagerQt.pri \
		/usr/lib/qt/mkspecs/modules/qt_phonon4qt5.pri \
		/usr/lib/qt/mkspecs/modules/qt_Prison.pri \
		/usr/lib/qt/mkspecs/modules/qt_QuickAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_Solid.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetUi.pri \
		/usr/lib/qt/mkspecs/modules/qt_ThreadWeaver.pri \
		/usr/lib/qt/mkspecs/features/qt_functions.prf \
		/usr/lib/qt/mkspecs/features/qt_config.prf \
		/usr/lib/qt/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt/mkspecs/features/toolchain.prf \
		/usr/lib/qt/mkspecs/features/default_pre.prf \
		/usr/lib/qt/mkspecs/features/resolve_config.prf \
		/usr/lib/qt/mkspecs/features/default_post.prf \
		/usr/lib/qt/mkspecs/features/qml_debug.prf \
		/usr/lib/qt/mkspecs/features/warn_on.prf \
		/usr/lib/qt/mkspecs/features/qt.prf \
		/usr/lib/qt/mkspecs/features/resources.prf \
		/usr/lib/qt/mkspecs/features/moc.prf \
		/usr/lib/qt/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt/mkspecs/features/uic.prf \
		/usr/lib/qt/mkspecs/features/unix/thread.prf \
		/usr/lib/qt/mkspecs/features/qmake_use.prf \
		/usr/lib/qt/mkspecs/features/file_copies.prf \
		/usr/lib/qt/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt/mkspecs/features/exceptions.prf \
		/usr/lib/qt/mkspecs/features/yacc.prf \
		/usr/lib/qt/mkspecs/features/lex.prf \
		DBOX-MTCT.pro \
		/usr/lib/libQt5PrintSupport.prl \
		/usr/lib/libQt5Widgets.prl \
		/usr/lib/libQt5Gui.prl \
		/usr/lib/libQt5Core.prl
	$(QMAKE) -o Makefile DBOX-MTCT.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
/usr/lib/qt/mkspecs/features/spec_pre.prf:
/usr/lib/qt/mkspecs/common/unix.conf:
/usr/lib/qt/mkspecs/common/linux.conf:
/usr/lib/qt/mkspecs/common/sanitize.conf:
/usr/lib/qt/mkspecs/common/gcc-base.conf:
/usr/lib/qt/mkspecs/common/gcc-base-unix.conf:
/usr/lib/qt/mkspecs/common/g++-base.conf:
/usr/lib/qt/mkspecs/common/g++-unix.conf:
/usr/lib/qt/mkspecs/qconfig.pri:
/usr/lib/qt/mkspecs/modules/qt_Attica.pri:
/usr/lib/qt/mkspecs/modules/qt_Baloo.pri:
/usr/lib/qt/mkspecs/modules/qt_BluezQt.pri:
/usr/lib/qt/mkspecs/modules/qt_KActivities.pri:
/usr/lib/qt/mkspecs/modules/qt_KActivitiesStats.pri:
/usr/lib/qt/mkspecs/modules/qt_KArchive.pri:
/usr/lib/qt/mkspecs/modules/qt_KAuth.pri:
/usr/lib/qt/mkspecs/modules/qt_KBookmarks.pri:
/usr/lib/qt/mkspecs/modules/qt_KCMUtils.pri:
/usr/lib/qt/mkspecs/modules/qt_KCodecs.pri:
/usr/lib/qt/mkspecs/modules/qt_KCompletion.pri:
/usr/lib/qt/mkspecs/modules/qt_KConfigCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KConfigGui.pri:
/usr/lib/qt/mkspecs/modules/qt_KConfigWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KCoreAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KCrash.pri:
/usr/lib/qt/mkspecs/modules/qt_KDBusAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KDeclarative.pri:
/usr/lib/qt/mkspecs/modules/qt_KDESu.pri:
/usr/lib/qt/mkspecs/modules/qt_KDNSSD.pri:
/usr/lib/qt/mkspecs/modules/qt_KEmoticons.pri:
/usr/lib/qt/mkspecs/modules/qt_KFileMetaData.pri:
/usr/lib/qt/mkspecs/modules/qt_KGlobalAccel.pri:
/usr/lib/qt/mkspecs/modules/qt_KGuiAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KHolidays.pri:
/usr/lib/qt/mkspecs/modules/qt_KHtml.pri:
/usr/lib/qt/mkspecs/modules/qt_KI18n.pri:
/usr/lib/qt/mkspecs/modules/qt_KIconThemes.pri:
/usr/lib/qt/mkspecs/modules/qt_KIdleTime.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOFileWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOGui.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_Kirigami2.pri:
/usr/lib/qt/mkspecs/modules/qt_KItemModels.pri:
/usr/lib/qt/mkspecs/modules/qt_KItemViews.pri:
/usr/lib/qt/mkspecs/modules/qt_KJobWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KJS.pri:
/usr/lib/qt/mkspecs/modules/qt_KJSApi.pri:
/usr/lib/qt/mkspecs/modules/qt_KJsEmbed.pri:
/usr/lib/qt/mkspecs/modules/qt_KNewStuff.pri:
/usr/lib/qt/mkspecs/modules/qt_KNewStuffCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KNotifications.pri:
/usr/lib/qt/mkspecs/modules/qt_KNotifyConfig.pri:
/usr/lib/qt/mkspecs/modules/qt_KNTLM.pri:
/usr/lib/qt/mkspecs/modules/qt_KParts.pri:
/usr/lib/qt/mkspecs/modules/qt_KPeople.pri:
/usr/lib/qt/mkspecs/modules/qt_KPeopleWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KPty.pri:
/usr/lib/qt/mkspecs/modules/qt_KRunner.pri:
/usr/lib/qt/mkspecs/modules/qt_KScreen.pri:
/usr/lib/qt/mkspecs/modules/qt_KService.pri:
/usr/lib/qt/mkspecs/modules/qt_KSyntaxHighlighting.pri:
/usr/lib/qt/mkspecs/modules/qt_KTextEditor.pri:
/usr/lib/qt/mkspecs/modules/qt_KTextWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KUnitConversion.pri:
/usr/lib/qt/mkspecs/modules/qt_KWallet.pri:
/usr/lib/qt/mkspecs/modules/qt_KWaylandClient.pri:
/usr/lib/qt/mkspecs/modules/qt_KWaylandServer.pri:
/usr/lib/qt/mkspecs/modules/qt_KWidgetsAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KWindowSystem.pri:
/usr/lib/qt/mkspecs/modules/qt_KXmlGui.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_core.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_designer_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_dtkcore.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_dtkwidget.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_dtkwm.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_help.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_help_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_location.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_location_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_network.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioning.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioningquick_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_script.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_script_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_scripttools.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sensors.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_texttospeech_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webchannel.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webengine.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webengine_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webkit.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/lib/qt/mkspecs/modules/qt_ModemManagerQt.pri:
/usr/lib/qt/mkspecs/modules/qt_NetworkManagerQt.pri:
/usr/lib/qt/mkspecs/modules/qt_phonon4qt5.pri:
/usr/lib/qt/mkspecs/modules/qt_Prison.pri:
/usr/lib/qt/mkspecs/modules/qt_QuickAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_Solid.pri:
/usr/lib/qt/mkspecs/modules/qt_SonnetCore.pri:
/usr/lib/qt/mkspecs/modules/qt_SonnetUi.pri:
/usr/lib/qt/mkspecs/modules/qt_ThreadWeaver.pri:
/usr/lib/qt/mkspecs/features/qt_functions.prf:
/usr/lib/qt/mkspecs/features/qt_config.prf:
/usr/lib/qt/mkspecs/linux-g++/qmake.conf:
/usr/lib/qt/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/qt/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt/mkspecs/features/toolchain.prf:
/usr/lib/qt/mkspecs/features/default_pre.prf:
/usr/lib/qt/mkspecs/features/resolve_config.prf:
/usr/lib/qt/mkspecs/features/default_post.prf:
/usr/lib/qt/mkspecs/features/qml_debug.prf:
/usr/lib/qt/mkspecs/features/warn_on.prf:
/usr/lib/qt/mkspecs/features/qt.prf:
/usr/lib/qt/mkspecs/features/resources.prf:
/usr/lib/qt/mkspecs/features/moc.prf:
/usr/lib/qt/mkspecs/features/unix/opengl.prf:
/usr/lib/qt/mkspecs/features/uic.prf:
/usr/lib/qt/mkspecs/features/unix/thread.prf:
/usr/lib/qt/mkspecs/features/qmake_use.prf:
/usr/lib/qt/mkspecs/features/file_copies.prf:
/usr/lib/qt/mkspecs/features/testcase_targets.prf:
/usr/lib/qt/mkspecs/features/exceptions.prf:
/usr/lib/qt/mkspecs/features/yacc.prf:
/usr/lib/qt/mkspecs/features/lex.prf:
DBOX-MTCT.pro:
/usr/lib/libQt5PrintSupport.prl:
/usr/lib/libQt5Widgets.prl:
/usr/lib/libQt5Gui.prl:
/usr/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile DBOX-MTCT.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/qt/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h graphics_view_zoom.h MinutiaeMarker/minutiaemarker.h mousefingerprintscene.h networktrainer.h minutiaechecker.h caffenetwork.h databasetester.h isoconverter.h qmatconverter.h QCustomPlot/qcustomplot.h extractiontester.h helper.h MinutiaeMarker/minutia.h ui_mainwindow.h Config/dbox_mtct_config.h Config/minutia_config.h MinutiaeMarker/minutiaemarker_settings.h MinutiaeMarker/Utils/minutiaemarker_dataaugmentationutils.h MinutiaeMarker/Config/minutiamarker_config.h image.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp graphics_view_zoom.cpp MinutiaeMarker/minutiaemarker.cpp mousefingerprintscene.cpp networktrainer.cpp minutiaechecker.cpp caffenetwork.cpp databasetester.cpp isoconverter.cpp QCustomPlot/qcustomplot.cpp extractiontester.cpp Config/dbox_mtct_config.cpp Config/minutia_config.cpp MinutiaeMarker/minutia.cpp MinutiaeMarker/Config/minutiaemarker_config.cpp MinutiaeMarker/minutiaemarker_settings.cpp MinutiaeMarker/Utils/minutiaemarker_dataaugmentationutils.cpp image.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/qt/mkspecs/features/data/dummy.cpp
	g++ -pipe -g -Wall -W -dM -E -o moc_predefs.h /usr/lib/qt/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_graphics_view_zoom.cpp moc_minutiaemarker.cpp moc_mousefingerprintscene.cpp moc_networktrainer.cpp moc_minutiaechecker.cpp moc_caffenetwork.cpp moc_databasetester.cpp moc_isoconverter.cpp moc_qcustomplot.cpp moc_extractiontester.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_graphics_view_zoom.cpp moc_minutiaemarker.cpp moc_mousefingerprintscene.cpp moc_networktrainer.cpp moc_minutiaechecker.cpp moc_caffenetwork.cpp moc_databasetester.cpp moc_isoconverter.cpp moc_qcustomplot.cpp moc_extractiontester.cpp
moc_mainwindow.cpp: QCustomPlot/qcustomplot.h \
		graphics_view_zoom.h \
		image.h \
		Config/dbox_mtct_config.h \
		Config/minutia_config.h \
		MinutiaeMarker/minutia.h \
		MinutiaeMarker/minutiaemarker.h \
		MinutiaeMarker/Utils/minutiaemarker_dataaugmentationutils.h \
		qmatconverter.h \
		mousefingerprintscene.h \
		MinutiaeMarker/minutiaemarker_settings.h \
		MinutiaeMarker/Config/minutiamarker_config.h \
		networktrainer.h \
		caffenetwork.h \
		minutiaechecker.h \
		helper.h \
		../../Git/fingerprint-preprocessing-lib/preprocessing_config.h \
		../../Git/fingerprint-preprocessing-lib/helper.h \
		extractiontester.h \
		../../Git/fingerprint-preprocessing-lib/preprocessing.h \
		../../Git/fingerprint-preprocessing-lib/preprocessing_global.h \
		../../Git/fingerprint-preprocessing-lib/orientationmap.h \
		../../Git/fingerprint-preprocessing-lib/gaborfiltermultithread.h \
		../../Git/fingerprint-preprocessing-lib/gaborthread.h \
		../../Git/fingerprint-preprocessing-lib/gaborfiltergpu.h \
		../../Git/fingerprint-preprocessing-lib/binarization.h \
		../../Git/fingerprint-preprocessing-lib/contrastenhancement.h \
		../../Git/fingerprint-preprocessing-lib/thinning.h \
		../../Git/fingerprint-preprocessing-lib/imagecontour.h \
		../../Git/fingerprint-preprocessing-lib/frequencymap.h \
		../../Git/fingerprint-preprocessing-lib/preprocessing_caffenetwork.h \
		../../Git/fingerprint-preprocessing-lib/mask.h \
		../../Git/fingerprint-preprocessing-lib/qualitymap.h \
		../../Git/fingerprint-extraction-lib/extraction.h \
		../../Git/fingerprint-extraction-lib/extraction_global.h \
		../../Git/fingerprint-extraction-lib/extraction_caffenetwork.h \
		../../Git/fingerprint-extraction-lib/extraction_config.h \
		../../Git/fingerprint-extraction-lib/crossingnumber.h \
		../../Git/fingerprint-extraction-lib/orientationfixer.h \
		../../Git/fingerprint-extraction-lib/neuralchecker.h \
		../../Git/fingerprint-extraction-lib/isoconverter.h \
		databasetester.h \
		../../Git/fingerprint-matching-lib/matcher.h \
		../../Git/fingerprint-matching-lib/matcher_global.h \
		../../Git/fingerprint-matching-lib/matcher_config.h \
		../../Git/fingerprint-matching-lib/matcher_isoconverter.h \
		../../Git/fingerprint-matching-lib/bozorth3m.h \
		mainwindow.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/peterhutas/QtProjects/DBOX-MTCT/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/peterhutas/QtProjects/DBOX-MTCT -I/opt/cuda/include -I/usr/local/include/suprema -I/home/peterhutas/Git/fingerprint-extraction-lib -I/home/peterhutas/Git/fingerprint-matching-lib -I/home/peterhutas/Git/fingerprint-preprocessing-lib -I/usr/include/qt -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/8.2.1 -I/usr/include/c++/8.2.1/x86_64-pc-linux-gnu -I/usr/include/c++/8.2.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.1/include-fixed -I/usr/include mainwindow.h -o moc_mainwindow.cpp

moc_graphics_view_zoom.cpp: graphics_view_zoom.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/peterhutas/QtProjects/DBOX-MTCT/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/peterhutas/QtProjects/DBOX-MTCT -I/opt/cuda/include -I/usr/local/include/suprema -I/home/peterhutas/Git/fingerprint-extraction-lib -I/home/peterhutas/Git/fingerprint-matching-lib -I/home/peterhutas/Git/fingerprint-preprocessing-lib -I/usr/include/qt -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/8.2.1 -I/usr/include/c++/8.2.1/x86_64-pc-linux-gnu -I/usr/include/c++/8.2.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.1/include-fixed -I/usr/include graphics_view_zoom.h -o moc_graphics_view_zoom.cpp

moc_minutiaemarker.cpp: MinutiaeMarker/Utils/minutiaemarker_dataaugmentationutils.h \
		qmatconverter.h \
		mousefingerprintscene.h \
		image.h \
		MinutiaeMarker/minutia.h \
		Config/minutia_config.h \
		MinutiaeMarker/minutiaemarker_settings.h \
		Config/dbox_mtct_config.h \
		MinutiaeMarker/Config/minutiamarker_config.h \
		MinutiaeMarker/minutiaemarker.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/peterhutas/QtProjects/DBOX-MTCT/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/peterhutas/QtProjects/DBOX-MTCT -I/opt/cuda/include -I/usr/local/include/suprema -I/home/peterhutas/Git/fingerprint-extraction-lib -I/home/peterhutas/Git/fingerprint-matching-lib -I/home/peterhutas/Git/fingerprint-preprocessing-lib -I/usr/include/qt -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/8.2.1 -I/usr/include/c++/8.2.1/x86_64-pc-linux-gnu -I/usr/include/c++/8.2.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.1/include-fixed -I/usr/include MinutiaeMarker/minutiaemarker.h -o moc_minutiaemarker.cpp

moc_mousefingerprintscene.cpp: image.h \
		MinutiaeMarker/minutia.h \
		Config/minutia_config.h \
		MinutiaeMarker/minutiaemarker_settings.h \
		Config/dbox_mtct_config.h \
		MinutiaeMarker/Config/minutiamarker_config.h \
		mousefingerprintscene.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/peterhutas/QtProjects/DBOX-MTCT/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/peterhutas/QtProjects/DBOX-MTCT -I/opt/cuda/include -I/usr/local/include/suprema -I/home/peterhutas/Git/fingerprint-extraction-lib -I/home/peterhutas/Git/fingerprint-matching-lib -I/home/peterhutas/Git/fingerprint-preprocessing-lib -I/usr/include/qt -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/8.2.1 -I/usr/include/c++/8.2.1/x86_64-pc-linux-gnu -I/usr/include/c++/8.2.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.1/include-fixed -I/usr/include mousefingerprintscene.h -o moc_mousefingerprintscene.cpp

moc_networktrainer.cpp: caffenetwork.h \
		networktrainer.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/peterhutas/QtProjects/DBOX-MTCT/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/peterhutas/QtProjects/DBOX-MTCT -I/opt/cuda/include -I/usr/local/include/suprema -I/home/peterhutas/Git/fingerprint-extraction-lib -I/home/peterhutas/Git/fingerprint-matching-lib -I/home/peterhutas/Git/fingerprint-preprocessing-lib -I/usr/include/qt -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/8.2.1 -I/usr/include/c++/8.2.1/x86_64-pc-linux-gnu -I/usr/include/c++/8.2.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.1/include-fixed -I/usr/include networktrainer.h -o moc_networktrainer.cpp

moc_minutiaechecker.cpp: caffenetwork.h \
		qmatconverter.h \
		helper.h \
		../../Git/fingerprint-preprocessing-lib/preprocessing_config.h \
		../../Git/fingerprint-preprocessing-lib/helper.h \
		minutiaechecker.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/peterhutas/QtProjects/DBOX-MTCT/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/peterhutas/QtProjects/DBOX-MTCT -I/opt/cuda/include -I/usr/local/include/suprema -I/home/peterhutas/Git/fingerprint-extraction-lib -I/home/peterhutas/Git/fingerprint-matching-lib -I/home/peterhutas/Git/fingerprint-preprocessing-lib -I/usr/include/qt -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/8.2.1 -I/usr/include/c++/8.2.1/x86_64-pc-linux-gnu -I/usr/include/c++/8.2.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.1/include-fixed -I/usr/include minutiaechecker.h -o moc_minutiaechecker.cpp

moc_caffenetwork.cpp: caffenetwork.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/peterhutas/QtProjects/DBOX-MTCT/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/peterhutas/QtProjects/DBOX-MTCT -I/opt/cuda/include -I/usr/local/include/suprema -I/home/peterhutas/Git/fingerprint-extraction-lib -I/home/peterhutas/Git/fingerprint-matching-lib -I/home/peterhutas/Git/fingerprint-preprocessing-lib -I/usr/include/qt -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/8.2.1 -I/usr/include/c++/8.2.1/x86_64-pc-linux-gnu -I/usr/include/c++/8.2.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.1/include-fixed -I/usr/include caffenetwork.h -o moc_caffenetwork.cpp

moc_databasetester.cpp: ../../Git/fingerprint-preprocessing-lib/preprocessing.h \
		../../Git/fingerprint-preprocessing-lib/preprocessing_global.h \
		../../Git/fingerprint-preprocessing-lib/preprocessing_config.h \
		../../Git/fingerprint-preprocessing-lib/helper.h \
		../../Git/fingerprint-preprocessing-lib/orientationmap.h \
		../../Git/fingerprint-preprocessing-lib/gaborfiltermultithread.h \
		../../Git/fingerprint-preprocessing-lib/gaborthread.h \
		../../Git/fingerprint-preprocessing-lib/gaborfiltergpu.h \
		../../Git/fingerprint-preprocessing-lib/binarization.h \
		../../Git/fingerprint-preprocessing-lib/contrastenhancement.h \
		../../Git/fingerprint-preprocessing-lib/thinning.h \
		../../Git/fingerprint-preprocessing-lib/imagecontour.h \
		../../Git/fingerprint-preprocessing-lib/frequencymap.h \
		../../Git/fingerprint-preprocessing-lib/preprocessing_caffenetwork.h \
		../../Git/fingerprint-preprocessing-lib/mask.h \
		../../Git/fingerprint-preprocessing-lib/qualitymap.h \
		../../Git/fingerprint-extraction-lib/extraction.h \
		../../Git/fingerprint-extraction-lib/extraction_global.h \
		../../Git/fingerprint-extraction-lib/extraction_caffenetwork.h \
		../../Git/fingerprint-extraction-lib/extraction_config.h \
		../../Git/fingerprint-extraction-lib/crossingnumber.h \
		../../Git/fingerprint-extraction-lib/orientationfixer.h \
		../../Git/fingerprint-extraction-lib/neuralchecker.h \
		../../Git/fingerprint-extraction-lib/isoconverter.h \
		../../Git/fingerprint-matching-lib/matcher.h \
		../../Git/fingerprint-matching-lib/matcher_global.h \
		../../Git/fingerprint-matching-lib/matcher_config.h \
		../../Git/fingerprint-matching-lib/matcher_isoconverter.h \
		../../Git/fingerprint-matching-lib/bozorth3m.h \
		qmatconverter.h \
		databasetester.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/peterhutas/QtProjects/DBOX-MTCT/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/peterhutas/QtProjects/DBOX-MTCT -I/opt/cuda/include -I/usr/local/include/suprema -I/home/peterhutas/Git/fingerprint-extraction-lib -I/home/peterhutas/Git/fingerprint-matching-lib -I/home/peterhutas/Git/fingerprint-preprocessing-lib -I/usr/include/qt -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/8.2.1 -I/usr/include/c++/8.2.1/x86_64-pc-linux-gnu -I/usr/include/c++/8.2.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.1/include-fixed -I/usr/include databasetester.h -o moc_databasetester.cpp

moc_isoconverter.cpp: isoconverter.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/peterhutas/QtProjects/DBOX-MTCT/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/peterhutas/QtProjects/DBOX-MTCT -I/opt/cuda/include -I/usr/local/include/suprema -I/home/peterhutas/Git/fingerprint-extraction-lib -I/home/peterhutas/Git/fingerprint-matching-lib -I/home/peterhutas/Git/fingerprint-preprocessing-lib -I/usr/include/qt -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/8.2.1 -I/usr/include/c++/8.2.1/x86_64-pc-linux-gnu -I/usr/include/c++/8.2.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.1/include-fixed -I/usr/include isoconverter.h -o moc_isoconverter.cpp

moc_qcustomplot.cpp: QCustomPlot/qcustomplot.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/peterhutas/QtProjects/DBOX-MTCT/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/peterhutas/QtProjects/DBOX-MTCT -I/opt/cuda/include -I/usr/local/include/suprema -I/home/peterhutas/Git/fingerprint-extraction-lib -I/home/peterhutas/Git/fingerprint-matching-lib -I/home/peterhutas/Git/fingerprint-preprocessing-lib -I/usr/include/qt -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/8.2.1 -I/usr/include/c++/8.2.1/x86_64-pc-linux-gnu -I/usr/include/c++/8.2.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.1/include-fixed -I/usr/include QCustomPlot/qcustomplot.h -o moc_qcustomplot.cpp

moc_extractiontester.cpp: ../../Git/fingerprint-preprocessing-lib/preprocessing.h \
		../../Git/fingerprint-preprocessing-lib/preprocessing_global.h \
		../../Git/fingerprint-preprocessing-lib/preprocessing_config.h \
		../../Git/fingerprint-preprocessing-lib/helper.h \
		../../Git/fingerprint-preprocessing-lib/orientationmap.h \
		../../Git/fingerprint-preprocessing-lib/gaborfiltermultithread.h \
		../../Git/fingerprint-preprocessing-lib/gaborthread.h \
		../../Git/fingerprint-preprocessing-lib/gaborfiltergpu.h \
		../../Git/fingerprint-preprocessing-lib/binarization.h \
		../../Git/fingerprint-preprocessing-lib/contrastenhancement.h \
		../../Git/fingerprint-preprocessing-lib/thinning.h \
		../../Git/fingerprint-preprocessing-lib/imagecontour.h \
		../../Git/fingerprint-preprocessing-lib/frequencymap.h \
		../../Git/fingerprint-preprocessing-lib/preprocessing_caffenetwork.h \
		../../Git/fingerprint-preprocessing-lib/mask.h \
		../../Git/fingerprint-preprocessing-lib/qualitymap.h \
		../../Git/fingerprint-extraction-lib/extraction.h \
		../../Git/fingerprint-extraction-lib/extraction_global.h \
		../../Git/fingerprint-extraction-lib/extraction_caffenetwork.h \
		../../Git/fingerprint-extraction-lib/extraction_config.h \
		../../Git/fingerprint-extraction-lib/crossingnumber.h \
		../../Git/fingerprint-extraction-lib/orientationfixer.h \
		../../Git/fingerprint-extraction-lib/neuralchecker.h \
		../../Git/fingerprint-extraction-lib/isoconverter.h \
		extractiontester.h \
		moc_predefs.h \
		/usr/bin/moc
	/usr/bin/moc $(DEFINES) --include /home/peterhutas/QtProjects/DBOX-MTCT/moc_predefs.h -I/usr/lib/qt/mkspecs/linux-g++ -I/home/peterhutas/QtProjects/DBOX-MTCT -I/opt/cuda/include -I/usr/local/include/suprema -I/home/peterhutas/Git/fingerprint-extraction-lib -I/home/peterhutas/Git/fingerprint-matching-lib -I/home/peterhutas/Git/fingerprint-preprocessing-lib -I/usr/include/qt -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/8.2.1 -I/usr/include/c++/8.2.1/x86_64-pc-linux-gnu -I/usr/include/c++/8.2.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.1/include-fixed -I/usr/include extractiontester.h -o moc_extractiontester.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		/usr/bin/uic \
		QCustomPlot/qcustomplot.h
	/usr/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		QCustomPlot/qcustomplot.h \
		graphics_view_zoom.h \
		image.h \
		Config/dbox_mtct_config.h \
		Config/minutia_config.h \
		MinutiaeMarker/minutia.h \
		MinutiaeMarker/minutiaemarker.h \
		MinutiaeMarker/Utils/minutiaemarker_dataaugmentationutils.h \
		qmatconverter.h \
		mousefingerprintscene.h \
		MinutiaeMarker/minutiaemarker_settings.h \
		MinutiaeMarker/Config/minutiamarker_config.h \
		networktrainer.h \
		caffenetwork.h \
		minutiaechecker.h \
		helper.h \
		../../Git/fingerprint-preprocessing-lib/preprocessing_config.h \
		../../Git/fingerprint-preprocessing-lib/helper.h \
		extractiontester.h \
		../../Git/fingerprint-preprocessing-lib/preprocessing.h \
		../../Git/fingerprint-preprocessing-lib/preprocessing_global.h \
		../../Git/fingerprint-preprocessing-lib/orientationmap.h \
		../../Git/fingerprint-preprocessing-lib/gaborfiltermultithread.h \
		../../Git/fingerprint-preprocessing-lib/gaborthread.h \
		../../Git/fingerprint-preprocessing-lib/gaborfiltergpu.h \
		../../Git/fingerprint-preprocessing-lib/binarization.h \
		../../Git/fingerprint-preprocessing-lib/contrastenhancement.h \
		../../Git/fingerprint-preprocessing-lib/thinning.h \
		../../Git/fingerprint-preprocessing-lib/imagecontour.h \
		../../Git/fingerprint-preprocessing-lib/frequencymap.h \
		../../Git/fingerprint-preprocessing-lib/preprocessing_caffenetwork.h \
		../../Git/fingerprint-preprocessing-lib/mask.h \
		../../Git/fingerprint-preprocessing-lib/qualitymap.h \
		../../Git/fingerprint-extraction-lib/extraction.h \
		../../Git/fingerprint-extraction-lib/extraction_global.h \
		../../Git/fingerprint-extraction-lib/extraction_caffenetwork.h \
		../../Git/fingerprint-extraction-lib/extraction_config.h \
		../../Git/fingerprint-extraction-lib/crossingnumber.h \
		../../Git/fingerprint-extraction-lib/orientationfixer.h \
		../../Git/fingerprint-extraction-lib/neuralchecker.h \
		../../Git/fingerprint-extraction-lib/isoconverter.h \
		databasetester.h \
		../../Git/fingerprint-matching-lib/matcher.h \
		../../Git/fingerprint-matching-lib/matcher_global.h \
		../../Git/fingerprint-matching-lib/matcher_config.h \
		../../Git/fingerprint-matching-lib/matcher_isoconverter.h \
		../../Git/fingerprint-matching-lib/bozorth3m.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		QCustomPlot/qcustomplot.h \
		graphics_view_zoom.h \
		image.h \
		Config/dbox_mtct_config.h \
		Config/minutia_config.h \
		MinutiaeMarker/minutia.h \
		MinutiaeMarker/minutiaemarker.h \
		MinutiaeMarker/Utils/minutiaemarker_dataaugmentationutils.h \
		qmatconverter.h \
		mousefingerprintscene.h \
		MinutiaeMarker/minutiaemarker_settings.h \
		MinutiaeMarker/Config/minutiamarker_config.h \
		networktrainer.h \
		caffenetwork.h \
		minutiaechecker.h \
		helper.h \
		../../Git/fingerprint-preprocessing-lib/preprocessing_config.h \
		../../Git/fingerprint-preprocessing-lib/helper.h \
		extractiontester.h \
		../../Git/fingerprint-preprocessing-lib/preprocessing.h \
		../../Git/fingerprint-preprocessing-lib/preprocessing_global.h \
		../../Git/fingerprint-preprocessing-lib/orientationmap.h \
		../../Git/fingerprint-preprocessing-lib/gaborfiltermultithread.h \
		../../Git/fingerprint-preprocessing-lib/gaborthread.h \
		../../Git/fingerprint-preprocessing-lib/gaborfiltergpu.h \
		../../Git/fingerprint-preprocessing-lib/binarization.h \
		../../Git/fingerprint-preprocessing-lib/contrastenhancement.h \
		../../Git/fingerprint-preprocessing-lib/thinning.h \
		../../Git/fingerprint-preprocessing-lib/imagecontour.h \
		../../Git/fingerprint-preprocessing-lib/frequencymap.h \
		../../Git/fingerprint-preprocessing-lib/preprocessing_caffenetwork.h \
		../../Git/fingerprint-preprocessing-lib/mask.h \
		../../Git/fingerprint-preprocessing-lib/qualitymap.h \
		../../Git/fingerprint-extraction-lib/extraction.h \
		../../Git/fingerprint-extraction-lib/extraction_global.h \
		../../Git/fingerprint-extraction-lib/extraction_caffenetwork.h \
		../../Git/fingerprint-extraction-lib/extraction_config.h \
		../../Git/fingerprint-extraction-lib/crossingnumber.h \
		../../Git/fingerprint-extraction-lib/orientationfixer.h \
		../../Git/fingerprint-extraction-lib/neuralchecker.h \
		../../Git/fingerprint-extraction-lib/isoconverter.h \
		databasetester.h \
		../../Git/fingerprint-matching-lib/matcher.h \
		../../Git/fingerprint-matching-lib/matcher_global.h \
		../../Git/fingerprint-matching-lib/matcher_config.h \
		../../Git/fingerprint-matching-lib/matcher_isoconverter.h \
		../../Git/fingerprint-matching-lib/bozorth3m.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

graphics_view_zoom.o: graphics_view_zoom.cpp graphics_view_zoom.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o graphics_view_zoom.o graphics_view_zoom.cpp

minutiaemarker.o: MinutiaeMarker/minutiaemarker.cpp MinutiaeMarker/minutiaemarker.h \
		MinutiaeMarker/Utils/minutiaemarker_dataaugmentationutils.h \
		qmatconverter.h \
		mousefingerprintscene.h \
		image.h \
		MinutiaeMarker/minutia.h \
		Config/minutia_config.h \
		MinutiaeMarker/minutiaemarker_settings.h \
		Config/dbox_mtct_config.h \
		MinutiaeMarker/Config/minutiamarker_config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o minutiaemarker.o MinutiaeMarker/minutiaemarker.cpp

mousefingerprintscene.o: mousefingerprintscene.cpp mousefingerprintscene.h \
		image.h \
		MinutiaeMarker/minutia.h \
		Config/minutia_config.h \
		MinutiaeMarker/minutiaemarker_settings.h \
		Config/dbox_mtct_config.h \
		MinutiaeMarker/Config/minutiamarker_config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mousefingerprintscene.o mousefingerprintscene.cpp

networktrainer.o: networktrainer.cpp networktrainer.h \
		caffenetwork.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o networktrainer.o networktrainer.cpp

minutiaechecker.o: minutiaechecker.cpp minutiaechecker.h \
		caffenetwork.h \
		qmatconverter.h \
		helper.h \
		../../Git/fingerprint-preprocessing-lib/preprocessing_config.h \
		../../Git/fingerprint-preprocessing-lib/helper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o minutiaechecker.o minutiaechecker.cpp

caffenetwork.o: caffenetwork.cpp caffenetwork.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o caffenetwork.o caffenetwork.cpp

databasetester.o: databasetester.cpp databasetester.h \
		../../Git/fingerprint-preprocessing-lib/preprocessing.h \
		../../Git/fingerprint-preprocessing-lib/preprocessing_global.h \
		../../Git/fingerprint-preprocessing-lib/preprocessing_config.h \
		../../Git/fingerprint-preprocessing-lib/helper.h \
		../../Git/fingerprint-preprocessing-lib/orientationmap.h \
		../../Git/fingerprint-preprocessing-lib/gaborfiltermultithread.h \
		../../Git/fingerprint-preprocessing-lib/gaborthread.h \
		../../Git/fingerprint-preprocessing-lib/gaborfiltergpu.h \
		../../Git/fingerprint-preprocessing-lib/binarization.h \
		../../Git/fingerprint-preprocessing-lib/contrastenhancement.h \
		../../Git/fingerprint-preprocessing-lib/thinning.h \
		../../Git/fingerprint-preprocessing-lib/imagecontour.h \
		../../Git/fingerprint-preprocessing-lib/frequencymap.h \
		../../Git/fingerprint-preprocessing-lib/preprocessing_caffenetwork.h \
		../../Git/fingerprint-preprocessing-lib/mask.h \
		../../Git/fingerprint-preprocessing-lib/qualitymap.h \
		../../Git/fingerprint-extraction-lib/extraction.h \
		../../Git/fingerprint-extraction-lib/extraction_global.h \
		../../Git/fingerprint-extraction-lib/extraction_caffenetwork.h \
		../../Git/fingerprint-extraction-lib/extraction_config.h \
		../../Git/fingerprint-extraction-lib/crossingnumber.h \
		../../Git/fingerprint-extraction-lib/orientationfixer.h \
		../../Git/fingerprint-extraction-lib/neuralchecker.h \
		../../Git/fingerprint-extraction-lib/isoconverter.h \
		../../Git/fingerprint-matching-lib/matcher.h \
		../../Git/fingerprint-matching-lib/matcher_global.h \
		../../Git/fingerprint-matching-lib/matcher_config.h \
		../../Git/fingerprint-matching-lib/matcher_isoconverter.h \
		../../Git/fingerprint-matching-lib/bozorth3m.h \
		qmatconverter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o databasetester.o databasetester.cpp

isoconverter.o: isoconverter.cpp ../../Git/fingerprint-extraction-lib/isoconverter.h \
		../../Git/fingerprint-extraction-lib/extraction_config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o isoconverter.o isoconverter.cpp

qcustomplot.o: QCustomPlot/qcustomplot.cpp QCustomPlot/qcustomplot.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qcustomplot.o QCustomPlot/qcustomplot.cpp

extractiontester.o: extractiontester.cpp extractiontester.h \
		../../Git/fingerprint-preprocessing-lib/preprocessing.h \
		../../Git/fingerprint-preprocessing-lib/preprocessing_global.h \
		../../Git/fingerprint-preprocessing-lib/preprocessing_config.h \
		../../Git/fingerprint-preprocessing-lib/helper.h \
		../../Git/fingerprint-preprocessing-lib/orientationmap.h \
		../../Git/fingerprint-preprocessing-lib/gaborfiltermultithread.h \
		../../Git/fingerprint-preprocessing-lib/gaborthread.h \
		../../Git/fingerprint-preprocessing-lib/gaborfiltergpu.h \
		../../Git/fingerprint-preprocessing-lib/binarization.h \
		../../Git/fingerprint-preprocessing-lib/contrastenhancement.h \
		../../Git/fingerprint-preprocessing-lib/thinning.h \
		../../Git/fingerprint-preprocessing-lib/imagecontour.h \
		../../Git/fingerprint-preprocessing-lib/frequencymap.h \
		../../Git/fingerprint-preprocessing-lib/preprocessing_caffenetwork.h \
		../../Git/fingerprint-preprocessing-lib/mask.h \
		../../Git/fingerprint-preprocessing-lib/qualitymap.h \
		../../Git/fingerprint-extraction-lib/extraction.h \
		../../Git/fingerprint-extraction-lib/extraction_global.h \
		../../Git/fingerprint-extraction-lib/extraction_caffenetwork.h \
		../../Git/fingerprint-extraction-lib/extraction_config.h \
		../../Git/fingerprint-extraction-lib/crossingnumber.h \
		../../Git/fingerprint-extraction-lib/orientationfixer.h \
		../../Git/fingerprint-extraction-lib/neuralchecker.h \
		../../Git/fingerprint-extraction-lib/isoconverter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o extractiontester.o extractiontester.cpp

dbox_mtct_config.o: Config/dbox_mtct_config.cpp Config/dbox_mtct_config.h \
		Config/minutia_config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dbox_mtct_config.o Config/dbox_mtct_config.cpp

minutia_config.o: Config/minutia_config.cpp Config/minutia_config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o minutia_config.o Config/minutia_config.cpp

minutia.o: MinutiaeMarker/minutia.cpp MinutiaeMarker/minutia.h \
		Config/minutia_config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o minutia.o MinutiaeMarker/minutia.cpp

minutiaemarker_config.o: MinutiaeMarker/Config/minutiaemarker_config.cpp MinutiaeMarker/Config/minutiamarker_config.h \
		Config/minutia_config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o minutiaemarker_config.o MinutiaeMarker/Config/minutiaemarker_config.cpp

minutiaemarker_settings.o: MinutiaeMarker/minutiaemarker_settings.cpp MinutiaeMarker/minutiaemarker_settings.h \
		Config/dbox_mtct_config.h \
		Config/minutia_config.h \
		MinutiaeMarker/Config/minutiamarker_config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o minutiaemarker_settings.o MinutiaeMarker/minutiaemarker_settings.cpp

minutiaemarker_dataaugmentationutils.o: MinutiaeMarker/Utils/minutiaemarker_dataaugmentationutils.cpp MinutiaeMarker/Utils/minutiaemarker_dataaugmentationutils.h \
		qmatconverter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o minutiaemarker_dataaugmentationutils.o MinutiaeMarker/Utils/minutiaemarker_dataaugmentationutils.cpp

image.o: image.cpp image.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o image.o image.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_graphics_view_zoom.o: moc_graphics_view_zoom.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_graphics_view_zoom.o moc_graphics_view_zoom.cpp

moc_minutiaemarker.o: moc_minutiaemarker.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_minutiaemarker.o moc_minutiaemarker.cpp

moc_mousefingerprintscene.o: moc_mousefingerprintscene.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mousefingerprintscene.o moc_mousefingerprintscene.cpp

moc_networktrainer.o: moc_networktrainer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_networktrainer.o moc_networktrainer.cpp

moc_minutiaechecker.o: moc_minutiaechecker.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_minutiaechecker.o moc_minutiaechecker.cpp

moc_caffenetwork.o: moc_caffenetwork.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_caffenetwork.o moc_caffenetwork.cpp

moc_databasetester.o: moc_databasetester.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_databasetester.o moc_databasetester.cpp

moc_isoconverter.o: moc_isoconverter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_isoconverter.o moc_isoconverter.cpp

moc_qcustomplot.o: moc_qcustomplot.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qcustomplot.o moc_qcustomplot.cpp

moc_extractiontester.o: moc_extractiontester.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_extractiontester.o moc_extractiontester.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

